# netlify.toml

[build]
  # command = "npm run build" # 如果你有构建命令
  publish = "docs"         # 你的 Docsify 内容所在的文件夹，或者是构建输出目录
  functions = "netlify/functions" # 明确指定函数目录

# 如果你的函数需要特定的 Node.js 版本
[functions]
  node_bundler = "esbuild" # 推荐使用 esbuild 以获得更快的构建速度
  # included_files = ["path/to/some/datafile/**"] # 如果函数需要其他文件

# [[redirects]] # 可选：如果你想让代理路径更简洁
#   from = "/api/gitalk-proxy/*"
#   to = "/.netlify/functions/gitalk-proxy/:splat"
#   status = 200